### ISSUE TITLE
blast-radius not working with latest terraform version

### ISSUE THREAD

**Issue by ltomes** [28mm/blast-radius#71]
blast-radius is not working with latest terraform version.
On inspection, blast-radius builds out terraform version 0.12.3, if a user is using a newer version of terraform they will get the following error:
` Error refreshing state: state snapshot was created by Terraform v0.12.12, which is newer than current v0.12.3; upgrade to Terraform v0.12.12 or greater to work with this state`

I have updated the terraform version in this PR:  #70 

Temporary mediation for compose users:
Create a docker-compose file like so:
```
version: '3.7'
services:
  graph:
    cap_add:
      - SYS_ADMIN
    image: gemini-blast-radius # 28mm/blast-radius
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - "./:/data"
```
Create a Dockerfile with the following properties:

```
ARG TF_VERSION=0.12.12
ARG PYTHON_VERSION=3.7

FROM hashicorp/terraform:$TF_VERSION AS terraform_latest
FROM 28mm/blast-radius

COPY --from=terraform_latest /bin/terraform /bin/terraform
```

The above compose file pulls blast-radius as is, and then forces the terraform 0.12.12 binary into the blast radius container.
